name: Build and Push to Artifact Registry

on:
  push:
    branches: ['main']

env:
  PROJECT_ID: bsky-bots-444900
  REGION: us-central1
  SERVICE: bsky-bots/bsky-bots-worker

jobs:
  build-push-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Docker auth'
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: 'Build and Push Container'
        run: |-
          DOCKER_TAG="$${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}"
          docker build --tag "${DOCKER_TAG}" .
          docker push "${DOCKER_TAG}"